# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fit parser
email: dev@benbr.com
description: > # this means to ignore newlines until "baseurl:"
  A FIT parser for Garmin devices (and many others), written in Groovy
github_username:  benbanerjeerichards
pygments: true

# Build settings
markdown: kramdown
